# Generated by Django 3.1 on 2020-08-16 11:07

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('faculty_name', models.CharField(max_length=20)),
                ('ta_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('marks', models.PositiveIntegerField()),
                ('courses', models.ManyToManyField(to='api_app.Course')),
            ],
        ),
    ]
