# Generated by Django 3.1 on 2020-08-16 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloger_name', models.CharField(max_length=30)),
                ('work_place', models.CharField(max_length=60)),
                ('work_post', models.TextField()),
                ('selected', models.CharField(max_length=60)),
                ('preparation', models.TextField()),
                ('salary', models.IntegerField()),
                ('interview_exp', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
